Desktop/store/book/urls.py
from django.urls import path
from . import views

app_name='book'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('<slug:category_slug>', views.book_list, name='book_by_category'),
    path('<int:id>/', views.book_detail, name='book_detail'),



] 
 

Desktop/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from book import views
app_name='book'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
   
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Desktop/store/book/models.py
from django.db import models
from django.urls import  reverse


# Create your models here.



class Category(models.Model):
    name=models.CharField(max_length=150,db_index=True)
    slug=models.SlugField(unique=True)
    class Meta:
        ordering=('-name',)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('book:book_by_category', args=[self.slug])

class Book(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    desc=models.TextField(db_index=True)
    publish=models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    publisher = models.CharField(max_length=500)
    author = models.CharField(max_length=500)

    class Meta:
        ordering=('-title',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
       return reverse('book:book_detail',args=[self.id,])

Desktop/store/book/views.py
from django.shortcuts import render,get_object_or_404
from .models import  Category,Book
from django.db.models import Q
# Create your views here.
def book_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    book = Book.objects.all()
    if request.method == "POST":
        search = request.POST.get('search')
        results = Book.objects.filter(Q(title__icontains=search)| Q(author__icontains=search))
        context={
            'result':results
        }
        return render(request,"book_list.html",context)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        book = book.filter(category=category)
    return render(request, 'book_list.html', {'categories':categories,
                                              'category':category,
                                              'book':book,
                                              })

def book_detail(request,id):
    book=get_object_or_404(Book,id=id)
    return render(request,'book_detail.html',{'book':book})

Desktop/store/book/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
      
    {% block content %}
            
    {% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

Desktop/store/book/templates/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
          <div class="col-sm-10">
            <div class="card">

              <div class="card-body">
                <h5 class="card-title">{{book.title}} by {{book.author}}</h5>
                <img src="{{book.image.url}}" class="card-img-top" width="400" height="450" alt="...">              
                <p class="card-text">{{book.desc}}</p>
                <p class="card-text" style="color: blue;">{{book.publisher}}</p>   
                    
              </div>
            </div>

{% endblock content %}

Desktop/store/book/templates/book_list.html
{%extends 'base.html' %}
{% block content %}
{% load static %}

<br>
<div>
    <h1>{% if category %}{{ category.name }}{% else %} BOOKS {% endif %}</h1>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Book Categories
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url "book:book_list" %}">Show All Books</a>
        {% for c in categories %}
        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% endfor %}
      </div>
  </div> 
    <form method = "POST" class="d-flex" style="margin:auto;max-width:300px">
      {% csrf_token %}
      <input class="form-control me-2" name="search" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  {% comment %} <div clas="card-body">
      <b>Sort By: - </b>
      <a href="{{ book.get_absolute_url }}?filter={{ filter }}&orderby=id">ID</a> |
      <a href="{{ book.get_absolute_url }}?filter={{ filter }}&orderby=price">Price</a> |
      <a href="{{ book.get_absolute_url }}?filter={{ filter }}&orderby=title">Title</a>
    </div>  {% endcomment %}
    {% if result %}
    <div class="row row-cols-2 row-cols-lg-4 g-0 g-lg-0">      
      {% for book in result %}
      <div class="col-sm-6">
          <h3> <a href="{{ book.get_absolute_url }}">{{book.title}}</h3></a>
            <div class="card" style="width: 20rem;">                         
          <img src="{{book.image.url}}" class="card-img-top" width="100px" height="350px" alt="...">  
          <div class="card-body">
            <h5 class="card-title">{{book.title}} by {{book.author}}</h5>
            <p class="card-text">Published by{{book.publisher}}</p>
            <p class="card-text" style="color: blue;">Rs {{book.amount}}</p>   
            <a href="" class="btn btn-primary">Buy</a>
          </div>
        </div>
      </div>
    </div>  
    {% endfor %}
    {% else %}

    
<div class="row row-cols-2 row-cols-lg-4 g-0 g-lg-0">
  <div class="col">
{% for book in book %}
     <h3> <a href="{{ book.get_absolute_url }}">{{book.title}}</h3></a>
     <div class="card" style="width: 20rem;">                         
        <img src="{{book.image.url}}" class="card-img-top" width="100px" height="350px" alt="...">  
      <div class="card-body">
        <h5 class="card-title">{{book.title}} by {{book.author}}</h5>
        <p class="card-text">Published by {{book.publisher}}</p>
        <p class="card-text" style="color: blue;">Rs {{book.amount}}</p>   
        <a href="" class="btn btn-primary">Buy</a>
        
    </div>
  </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}